#!/usr/bin/osascript

if application "Terminal" is frontmost then tell application "System Events" to keystroke "k" using command down
if application "iTerm" is frontmost then tell application "System Events" to keystroke "k" using command down
